# This is a basic workflow to help you get started with Actions

name: lint

on: [push, pull_request]

jobs:
  clj-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: echo
      run: echo ${{ github.event.pull_request.base.sha||github.event.before }}
    - name :
      if : ${{ GITHUB_REF#refs/heads/ == 'master' }}
      run: echo ${{ github.event.before }}
    - uses: xcoo/clj-lint-action@v1.1.2
      with:
        linters: "\"all\""
        github_token: ${{ secrets.GITHUB_TOKEN }}
        runner: ":leiningen"
        base_sha: ${{ github.event.pull_request.base.sha||github.event.before }}
        eastwood_linters: "[:all]"
