# This is a basic workflow to help you get started with Actions

name: lint

on: [push, pull_request]

jobs:
  clj-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name : master base sha
      id : master_base_sha
      if : github.ref  == 'refs/heads/master'
      run: echo  "::set-output name=base_sha::${{ github.event.before }}"
    - name : name2
      run : echo ${{ steps.master_base_sha.outputs.base_sha }}
    - uses: niyarin-another/clj-lint-action-1@d1.1.3
      with:
        linters: "\"all\""
        github_token: ${{ secrets.GITHUB_TOKEN }}
        runner: ":leiningen"
        base_sha: ${{ github.event.pull_request.base.sha||secrets.GITHUB_TOKEN }}
        eastwood_linters: "[:all]"
