# This is a basic workflow to help you get started with Actions

name: lint

on: [push, pull_request]

jobs:
  clj-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: onpush
      if: github.event_name == 'push'
      env:
          BASE_SHA: ${{ github.event.before }}
    - name: onpull_request
      if: github.event_name == 'pull_request'
      env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
    - name: echo output
      run: |
          echo ${{ BASE_SHA }}
    - uses: xcoo/clj-lint-action@v1.1.1
      with:
        linters: "\"all\""
        github_token: ${{ secrets.GITHUB_TOKEN }}
        runner: ":leiningen"
        base_sha: ${{ github.event.pull_request.base.sha }}
        eastwood_linters: "[:all]"
