# This is a basic workflow to help you get started with Actions

name: lint

on: [push, pull_request]

jobs:
  clj-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: piyo
      id: getfile2
      run: echo "::set-output name=files::$(git diff --name-only  | xargs)"
    - name: get changed files
      id: getfile
      run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | xargs)"
    - uses: technote-space/get-diff-action@v1
      id: git_diff
      with:
        SUFFIX_FILTER: .clj
        SEPARATOR: ' '
    - name: echo output
      run: |
          echo ${{ github.event.pull_request.base.sha }}
    - uses: xcoo/clj-lint-action@v1.1.1
      with:
        linters: "\"all\""
        github_token: ${{ secrets.GITHUB_TOKEN }}
        runner: ":leiningen"
        base_sha: ${{ github.event.pull_request.base.sha }}
        eastwood_linters: "[:all]"
